<!DOCTYPE html>
<html lang="en">

<head>
    <!-- cv-generator © <?=date('Y')?> | Krystian Borowicz -->
    
    <title><?=$this->pageTitle?></title>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="height=device-height, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="author" content="Oskar Zborowski, Krystian Borowicz">

    <meta name="theme-color" content="<?=$this->topnaBg?>">
    <meta name="msapplication-navbutton-color" content="<?=$this->topnavBg?>">
    <meta name="apple-mobile-web-app-status-bar-style" content="<?=$this->topnavBg?>">

    <link rel="stylesheet" href="<?=$this->asset('css/style.css')?>">
    <link rel="stylesheet" href="<?=$this->asset('icons/icons.css')?>">
</head>