<?php $this->include('head.phtml') ?>
<body>
    <main class="main">
        <nav class="main__topnav">
            <div class="topnav__user">
                <span id="js-user-name"><?=$this->user->getName()?></span>
                <span id="js-user-lastname"><?=$this->user->getLastname()?></span>
            </div>
            <div class="topnav__buttons">
                <button type="button" class="btn btn--light"
                    onclick="document.location.href='<?=$this->route('logout')?>'">log out</button>
                <button type="button" class="btn btn--light" id="js-save-btn">save</button>
                <button type="submit" class="btn" id="js-submit-btn"
                    onclick="window.open('<?=$this->route('generate', ['id' => $this->user->getId()])?>', '_blank')">generate CV</button>
            </div>
        </nav>
        <div class="main__data-group">
            <div class="cv-image">
                <?php 
                if(empty($this->user->getImageFile())) {
                    $imageUrl = '';
                } else {
                    $imageUrl = $this->route('open-image', ['imageFile' => $this->user->getImageFile()]);
                }
                ?>
                <img src="<?=$imageUrl?>" class="cv-image__image" id="js-user-image">
                <input type="file" id="js-image-upload-input" accept="image/*" class="cv-image__select">
            </div>
            <div class="row row--right row--1-3" style="margin-top: 0">
                <input type="text" class="form-control" placeholder="Name" id="js-basedata-name">
                <input type="text" class="form-control" placeholder="Lastname" id="js-basedata-lastname">
            </div>
            <div class="row row--right row--1-3">
                <input type="text" class="form-control" placeholder="Birth date DD.MM.YYYY" id="js-basedata-birth-date">
                <input type="text" class="form-control" placeholder="Phone number" id="js-basedata-phone-number">
            </div>
            <div class="row row--right row--2-3">
                <input type="text" class="form-control" placeholder="Email" id="js-basedata-email">
            </div>
            <div class="row row--right row--1-3">
                <input type="text" class="form-control" placeholder="Street and House number" id="js-basedata-street-and-house-number">
                <input type="text" class="form-control" placeholder="Zip code and town" id="js-basedata-town-and-zipcode">
            </div>
            <div class="row row--1">
                <textarea class="form-control form-control--textarea" placeholder="RODO" id="js-basedata-rodo"></textarea>
            </div>
            <div class="row row--1">
                <input type="text" class="form-control" placeholder="GitHub link" id="js-basedata-github">
            </div>
        </div>
        <div class="main__data-group">
            <div class="header">Skills</div>
            <div id="js-skills"></div>
            <div class="row">
                <button type="button" class="btn btn--light" id="js-skills-add-btn">add</button>
            </div>
        </div>
        <div class="main__data-group">
            <div class="header">Interests</div>
            <div id="js-interests"></div>
            <div class="row">
                <button type="button" class="btn btn--light" id="js-interests-add-btn">add</button>
            </div>
        </div>
        <div class="main__data-group">
            <div class="header">Employment history</div>
            <div id="js-employment-history"></div>
            <div class="row">
                <button type="button" class="btn btn--light" id="js-employment-add-btn">add</button>
            </div>
        </div>
        <div class="main__data-group">
            <div class="header">Education history</div>
            <div id="js-education-history"></div>
            <div class="row">
                <button type="button" class="btn btn--light" id="js-education-add-btn">add</button>
            </div>
        </div>
        <div class="main__loading-overlay" id="js-loading-overlay">
            <div class="loader"></div>
        </div>
    </main>
    <div class="banner">
        <b>CV Generator</b>&nbsp;by&nbsp;<a href="https://github.com/Grubix" class="link" target="_blank">Grubix</a>
    </div>

    <script>window.csrf='<?=$this->csrfToken()?>';</script>
    <script src="<?=$this->asset('js/base/utils.js')?>"></script>
    <script src="<?=$this->asset('js/base/anime.js')?>"></script>
    <script src="<?=$this->asset('js/app.js')?>"></script>
</body>
</html>