<html>
<head>
    <meta http-equiv="Content-Type" content="charset=utf-8"/>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div id="left">
        <img src="<?=$this->imageUrl?>" style="width: 100%"/>
        <div style="background-color: #022c25; padding: 10px">
            <div class="info-header">ADRES</div>
            <div class="info">
                <?=$this->street . $this->houseNumber?><br>
                <?=$this->zipDode . $this->town?>
            </div>
            <div class="info-header">KONTAKT</div>
            <div class="info">
                <?=$this->phoneNumber?><br>
                <?=$this->email?>
            </div>
            <div class="info-header">DATA URODZENIA</div>
            <div class="info">
                <?=$this->birthDate?>
            </div>
        </div>
        <div class="info-header" style="padding-left:10px; padding-top: 25px;">UMIEJĘTNOŚCI</div>
        <div id="skills" style="margin-top: 5px">
            <table>
                <?php foreach ($this->skills as $s) : ?>
                    <tr>
                        <td class="skill-tick"><img src="tick.png"></td>
                        <td class="skill"><?=$s?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
        <div class="info-header" style="padding-left:10px; padding-top: 25px;">ZAINTERESOWANIA</div>
        <div id="skills" style="margin-top: 5px">
            <table>
                <?php foreach ($this->interests as $i) : ?>
                    <tr>
                        <td class="skill-tick"><img src="tick.png"></td>
                        <td class="skill"><?=$i?></td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
    <div id="right">
        <div class="name"><?=$this->name . $this->lastname?></div><br>
        <div style="margin-top: 20px; font-size: 20px; font-family: \'bold\'">HISTORIA ZATRUDNIENIA</div>
        <hr style="margin: 0; padding: 0; height: 0; border: none; border-top: 1px solid #000">

        <?php foreach ($this->employmentHistory as $emp) : ?>
            <div style="text-align: left; font-size: 13px; color: grey; font-family: \'regular\'">
                <?=$emp->period?>
            </div>
            <div style="font-size: 13px; font-family: \'black\'">
                <?=$emp->title?>
            </div>
            <div style="font-size: 13px; font-family: \'regular\'">
                <?=$emp->description?>
            </div><br>
        <?php endforeach; ?>

        <div style="margin-top: 20px; font-size: 20px; font-family: \'bold\'">WYKSZTAŁCENIE</div>
        <hr style="margin: 0; padding: 0; height: 0; border: none; border-top: 1px solid #000">

        <?php foreach ($this->educationHistory as $edu) : ?>
            <div style="text-align: left; font-size: 13px; color: grey; font-family: \'regular\'">
                <?=$edu->period?>
            </div>
            <div style="font-size: 13px; font-family: \'black\'">
                <?=$edu->title?>
            </div>
            <div style="font-size: 13px; font-family: \'regular\'">
                <?=$edu->description?>
            </div><br>
        <?php endforeach; ?>

        <div style="position: absolute; bottom: 0; color: grey; font-size: 10px"><?=$this->rodo?></div>
    </div>
</body>
</html>