<html>
<head>
    <title>CV | <?=$this->user->getFullName()?></title>
    <meta name="author" content="<?=$this->user->getFullName()?>">
    <meta http-equiv="Content-Type" content="charset=utf-8"/>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div id="left">
        <?php
            $path = IMAGES_DIR . $this->user->getImageFile();
            $src = ''; //TODO można dać jakiejs domyslne zdjecie

            if(file_exists($path) && is_file($path)) {
                $type = pathinfo($path)['extension'];
                $data = file_get_contents($path);
                $src = 'data:image/' . $type . ';base64,' . base64_encode($data);
            }
        ?>
        <img src="<?=$src?>" style="width: 100%"/>
        <div style="background-color: #022c25; padding: 10px">
            <div class="info-header">ADRES</div>
            <div class="info">
                <?=$this->user->getAdressStreetAndHouseNumber()?><br>
                <?=$this->user->getAdressTownAndZipCode()?>
            </div>
            <div class="info-header">KONTAKT</div>
            <div class="info">
                <?=$this->user->getPhoneNumber()?><br>
                <?=$this->user->getEmail()?>
            </div>
            <div class="info-header">DATA URODZENIA</div>
            <div class="info">
                <?=$this->user->getBirthDate()->format('d.m.Y')?>
            </div>
            <?php if(!empty($this->user->getGithubLink())) : ?>
            <div class="info-header">GITHUB</div>
            <div class="info">
                <a href="<?=$this->user->getGithubLink()?>">
                    github.com/<?=basename($this->user->getGithubLink())?>
                </a>
            </div>
            <?php endif; ?>
        </div>
        <div class="info-header" style="padding-left:10px; padding-top: 25px;">UMIEJĘTNOŚCI</div>
        <div id="skills" style="margin-top: 5px">
            <table>
                <?php 
                if(!empty($this->user->getSkills())) :
                foreach ($this->user->getSkills() as $s) :
                ?>
                    <tr>
                        <td class="skill-tick"><img src="img/tick.png"></td>
                        <td class="skill"><?=$s?></td>
                    </tr>
                <?php endforeach; endif; ?>
            </table>
        </div>
        <div class="info-header" style="padding-left:10px; padding-top: 25px;">ZAINTERESOWANIA</div>
        <div id="skills" style="margin-top: 5px">
            <table>
                <?php 
                if(!empty($this->user->getInterests())) :
                foreach ($this->user->getInterests() as $i) : 
                ?>
                    <tr>
                        <td class="skill-tick"><img src="img/tick.png"></td>
                        <td class="skill"><?=$i?></td>
                    </tr>
                <?php endforeach; endif; ?>
            </table>
        </div>
    </div>
    <div id="right">
        <div class="name"><?=$this->user->getFullName()?></div><br>
        <div style="margin-top: 20px; font-size: 20px; font-family: lato-bold">HISTORIA ZATRUDNIENIA</div>
        <hr style="margin: 0; padding: 0; height: 0; border: none; border-top: 1px solid #000">

        <?php 
        if(!empty($this->user->getEmploymentHistory())) :
        foreach ($this->user->getEmploymentHistory() as $emp) : 
        ?>
            <br><div style="text-align: left; font-size: 13px; color: grey; font-family: lato-regular">
                <?=$emp['period']?>
            </div>
            <div style="font-size: 13px; font-family: lato-black">
                <?=$emp['title']?>
            </div>
            <div style="font-size: 13px; font-family: lato-regular">
                <?=$emp['description']?>
            </div>
        <?php endforeach; endif; ?>
        <br>

        <div style="margin-top: 20px; font-size: 20px; font-family: lato-bold">WYKSZTAŁCENIE</div>
        <hr style="margin: 0; padding: 0; height: 0; border: none; border-top: 1px solid #000">

        <?php 
        if(!empty($this->user->getEducationHistory())) :
        foreach ($this->user->getEducationHistory() as $edu) : 
        ?>
            <br><div style="text-align: left; font-size: 13px; color: grey; font-family: lato-regular">
                <?=$edu['period']?>
            </div>
            <div style="font-size: 13px; font-family: lato-black">
                <?=$edu['title']?>
            </div>
            <div style="font-size: 13px; font-family: lato-regular">
                <?=$edu['description']?>
            </div>
        <?php endforeach; endif; ?>

        <div style="position: absolute; bottom: 0; color: grey; font-size: 10px"><?=$this->user->getRodo()?></div>
    </div>
</body>
</html>